const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const winRoot=$("#windows"),iconRoot=$("#icons"),appRoot=$("#apps"),dockRoot=$("#dock"),launcherEl=$("#launcher"),searchEl=$("#search"),clockEl=$("#clock");
const power=$("#power"),setup=$("#setup"),boot=$("#boot"),desktop=$("#desktop"),lock=$("#lock"),powerBtn=$("#powerBtn"),setupContinue=$("#setupContinue"),chime=$("#bootChime");
const A={
about:{n:"About nexOS",i:"◈",w:480,h:320,v:'<div class="welcome"><h1>nexOS</h1><p class="muted">KDE Plasma × macOS-inspired web desktop.</p><p>Glass panels, a dock, draggable windows and real little apps.</p><p class="muted">nexOS 0.2 • browser edition</p></div>'},
files:{n:"nexView",i:"▣",w:580,h:380,v:'<div class="rows"><h2>Home</h2><div>📁 Documents <span>Folder</span></div><div>🖼 Pictures <span>Folder</span></div><div>⬇ Downloads <span>Folder</span></div></div>'},
browser:{n:"nexite",i:"◎",w:760,h:500,v:'<div class="browser"><div class="browserbar"><button id="back">‹</button><button id="forward">›</button><input id="url" value="https://example.com" placeholder="Search or enter address"><button id="go">Open</button></div><div class="browserinfo"><strong>nexOS Browser</strong><span id="uvStatus">nexite • starting Ultraviolet…</span></div><div class="browserview"><div id="browserHome" class="browser-home"><div class="browser-mark">◎</div><h2>Browse the web</h2><p>nexOS sends the address through Ultraviolet first, then loads the proxied result inside this browser window.</p><button id="browserOpen">Open proxied page ↗</button><small>proxied with UV + a Bare transport • no direct site URL is placed in the iframe</small></div><iframe id="uvFrame" title="nexOS proxied browser" referrerpolicy="no-referrer"></iframe></div></div>',o:initBrowser},
notes:{n:"nexJot",i:"▤",w:520,h:410,v:'<textarea id="notes" placeholder="Start typing…"></textarea>',o:()=>{const n=$("#notes");n.value=localStorage.nexNotes||"";n.oninput=()=>localStorage.nexNotes=n.value}},
settings:{n:"Settings",i:"⚙",w:720,h:520,v:'<div class="settings-shell"><aside class="settings-nav"><button data-page="appearance" class="active">🎨 <span>Appearance</span></button><button data-page="wallpaper">🖼 <span>Wallpaper</span></button><button data-page="desktopPage">🖥 <span>Desktop</span></button><button data-page="dockPage">▰ <span>Dock</span></button><button data-page="accessPage">♿ <span>Accessibility</span></button><button data-page="aboutPage">ⓘ <span>About</span></button></aside><div class="settings-content"><div id="appearance" class="settings-page"><h1>Appearance</h1><p>Customize how nexOS looks.</p><section><h3>Theme</h3><label>Color scheme <select id="settingTheme"><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Accent color <select id="settingAccent"><option value="blue">Blue</option><option value="violet">Violet</option><option value="pink">Pink</option></select></label></section></div><div id="wallpaper" class="settings-page hidden"><h1>Wallpaper</h1><p>Choose a desktop background.</p><div class="wall-grid"><button data-setting="default" class="wall-card wall-default">Default</button><button data-setting="midnight" class="wall-card wall-midnight">Midnight</button><button data-setting="sunset" class="wall-card wall-sunset">Sunset</button><button data-setting="aurora" class="wall-card wall-aurora">Aurora</button><button data-setting="ocean" class="wall-card wall-ocean">Ocean</button><button data-setting="rose" class="wall-card wall-rose">Rose</button><button data-setting="forest" class="wall-card wall-forest">Forest</button><button data-setting="mono" class="wall-card wall-mono">Mono</button></div></div><div id="desktopPage" class="settings-page hidden"><h1>Desktop</h1><p>Control your desktop layout.</p><section><label>Icon size <input id="settingIconSize" type="range" min="60" max="110" value="75"></label><button id="resetIcons">Reset icon positions</button></section><section><h3>Clock</h3><label class="check"><input id="settingClock24" type="checkbox"> 24-hour clock</label></section></div><div id="dockPage" class="settings-page hidden"><h1>Dock</h1><p>Customize the bottom dock.</p><section><label>Dock position <span>Bottom center</span></label><label>Dock icon size <input type="range" min="40" max="64" value="48"></label><label class="check"><input type="checkbox" checked> Show dock</label></section></div><div id="accessPage" class="settings-page hidden"><h1>Accessibility</h1><p>Make nexOS easier to use.</p><section><label class="check"><input type="checkbox"> Reduce motion</label><label class="check"><input type="checkbox"> Larger text</label><label class="check"><input type="checkbox"> High contrast</label></section></div><div id="aboutPage" class="settings-page hidden"><h1>About nexOS</h1><p>nexOS 0.2 • browser edition</p><p class="muted">A glassy web desktop inspired by KDE Plasma and GNOME.</p></div></div></div>',o:initSettings},
calculator:{n:"nexCalc",i:"⌗",w:350,h:430,v:'<div class="calc"><output id="out">0</output>'+["7","8","9","/","4","5","6","-","1","2","3","+","0",".","=","*"].map(x=>'<button data-k="'+x+'">'+x+"</button>").join("")+'<button data-k="C">C</button></div>',o:initCalc},
terminal:{n:"nexTerm",i:"⌘",w:600,h:390,v:'<div class="term" id="terminal">nexOS Terminal v0.1<br><span class="muted">type help</span><br>nex@web:~$ <input id="cmd" autocomplete="off"></div>',o:initTerminal}
};
let z=20,count=0;
function openApp(id){const old=$('.window[data-app="'+id+'"]');if(old){old.style.display="flex";focus(old);return}const a=A[id];if(!a)return;const w=document.createElement("section");w.className="window";w.dataset.app=id;w.style.width=a.w+"px";w.style.height=a.h+"px";w.style.left=120+(count++%5)*30+"px";w.style.top=70+(count%5)*25+"px";w.style.zIndex=++z;w.innerHTML='<div class="title"><div class="traffic"><button class="x"></button><button class="m"></button><button class="g"></button></div><strong>'+a.n+'</strong></div><div class="body">'+a.v+'</div><div class="resize"></div>';winRoot.appendChild(w);requestAnimationFrame(()=>w.classList.add("shown"));wireWindow(w);if(a.o)a.o();renderDock()}
function focus(w){w.style.zIndex=++z}
function wireWindow(w){w.onpointerdown=()=>focus(w);w.querySelector(".x").onclick=()=>{w.remove();renderDock()};w.querySelector(".m").onclick=()=>w.style.display="none";w.querySelector(".g").onclick=()=>w.classList.toggle("max");const bar=w.querySelector(".title");let drag=null;bar.onpointerdown=e=>{if(e.target.tagName==="BUTTON"||w.classList.contains("max"))return;drag=[e.clientX-parseFloat(w.style.left),e.clientY-parseFloat(w.style.top)];bar.setPointerCapture(e.pointerId)};bar.onpointermove=e=>{if(drag){w.style.left=Math.max(3,e.clientX-drag[0])+"px";w.style.top=Math.max(45,e.clientY-drag[1])+"px"}};bar.onpointerup=()=>drag=null;const r=w.querySelector(".resize");let size=null;r.onpointerdown=e=>{size=[e.clientX,w.offsetWidth,e.clientY,w.offsetHeight];r.setPointerCapture(e.pointerId)};r.onpointermove=e=>{if(size&&!w.classList.contains("max")){w.style.width=Math.max(300,size[1]+e.clientX-size[0])+"px";w.style.height=Math.max(180,size[3]+e.clientY-size[2])+"px"}};r.onpointerup=()=>size=null}
function renderDock(){dockRoot.innerHTML="";Object.keys(A).forEach(id=>{if($('.window[data-app="'+id+'"]')){const b=document.createElement("button");b.textContent=A[id].i;b.title=A[id].n;b.onclick=()=>openApp(id);dockRoot.appendChild(b)}})}
function initSettings(){const theme=$("#settingTheme"),accent=$("#settingAccent"),size=$("#settingIconSize"),clock24=$("#settingClock24");const wall=localStorage.nexWall||"default";theme.value=localStorage.nexTheme||"dark";accent.value=localStorage.nexAccent||"blue";size.value=localStorage.nexIconSize||75;clock24.checked=localStorage.nexClock24==="1";const apply=()=>{document.body.classList.toggle("light",theme.value==="light");document.body.dataset.accent=accent.value;document.body.dataset.wall=localStorage.nexWall||"default";iconRoot.style.setProperty("--icon-size",size.value+"px");localStorage.nexTheme=theme.value;localStorage.nexAccent=accent.value;localStorage.nexIconSize=size.value;localStorage.nexClock24=clock24.checked?"1":"0";updateClock()};[theme,accent].forEach(x=>x.addEventListener("change",apply));size.addEventListener("input",apply);clock24.addEventListener("change",apply);$("#resetIcons").onclick=()=>{localStorage.removeItem("nexIconPositions");location.reload()};$(".settings-nav button").forEach(b=>b.onclick=()=>{$(".settings-page").forEach(p=>p.classList.add("hidden"));$("#"+b.dataset.page).classList.remove("hidden");$(".settings-nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("[data-setting]").forEach(b=>b.onclick=()=>{const k=b.dataset.setting;document.body.dataset.wall=k;localStorage.nexWall=k;$("[data-setting]").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$('[data-setting="'+wall+'"]')?.classList.add("active");apply()}
function saveIconPositions(){const p={};$(".icon").forEach(d=>p[d.dataset.app]={left:d.style.left,top:d.style.top});localStorage.nexIconPositions=JSON.stringify(p)}
function makeIconMovable(d,id){d.dataset.app=id;let drag=null,moved=false;d.ondblclick=()=>openApp(id);d.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();$(".icon").forEach(x=>x.classList.remove("selected"));d.classList.add("selected");const r=d.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top,startX:e.clientX,startY:e.clientY};moved=false;d.setPointerCapture(e.pointerId)};d.onpointermove=e=>{if(!drag)return;e.preventDefault();const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;if(!moved)return;const root=iconRoot.getBoundingClientRect();d.style.left=Math.max(0,e.clientX-root.left-drag.x)+"px";d.style.top=Math.max(0,e.clientY-root.top-drag.y)+"px"};d.onpointerup=e=>{if(!drag)return;e.preventDefault();if(moved)saveIconPositions();drag=null};d.onpointercancel=()=>{drag=null}}
function populate(){const saved=JSON.parse(localStorage.nexIconPositions||"{}");Object.entries(A).forEach(([id,a])=>{const d=document.createElement("button");d.className="icon";d.innerHTML="<b>"+a.i+"</b><small>"+a.n+"</small>";if(saved[id]){d.style.left=saved[id].left;d.style.top=saved[id].top}else{const n=Object.keys(A).indexOf(id);d.style.left=(n%2)*95+"px";d.style.top=Math.floor(n/2)*90+"px"}makeIconMovable(d,id);iconRoot.appendChild(d);const x=document.createElement("button");x.className="app";x.dataset.app=id;x.innerHTML="<b>"+a.i+"</b><small>"+a.n.replace("About ","")+"</small>";x.onclick=()=>{openApp(id);launcherEl.classList.add("hidden")};appRoot.appendChild(x)})}
$("#launch").onclick=()=>launcherEl.classList.toggle("hidden");$("#brand").onclick=()=>launcherEl.classList.remove("hidden");document.querySelectorAll("[data-app]").forEach(b=>b.onclick=()=>openApp(b.dataset.app));searchEl.oninput=()=>$$(".app").forEach(x=>x.classList.toggle("hidden",!x.textContent.toLowerCase().includes(searchEl.value.toLowerCase())));document.addEventListener("keydown",e=>{if(e.key==="Escape")launcherEl.classList.add("hidden")});
function updateClock(){clockEl.textContent=new Intl.DateTimeFormat([],{weekday:"short",hour:"numeric",minute:"2-digit"}).format(new Date())}setInterval(updateClock,1000);updateClock();
function updateLockClock(){const d=new Date();$("#lockTime").textContent=new Intl.DateTimeFormat([],{hour:"numeric",minute:"2-digit"}).format(d);$("#lockDate").textContent=new Intl.DateTimeFormat([],{weekday:"long",month:"long",day:"numeric"}).format(d)}setInterval(updateLockClock,1000);
function initCalc(){let v="0";$$("[data-k]").forEach(b=>b.onclick=()=>{const k=b.dataset.k;if(k==="C")v="0";else if(k==="="){try{v=String(Function("return "+v)())}catch{v="Error"}}else v=v==="0"&&!"+-*/.".includes(k)?k:v+k;$("#out").textContent=v})}
function initTerminal(){const input=$("#cmd"),terminal=$("#terminal");input.focus();input.onkeydown=e=>{if(e.key!=="Enter")return;const q=input.value.trim(),x=document.createElement("div");x.textContent="nex@web:~$ "+q+"  "+(q==="help"?"help clear date whoami neofetch":q==="whoami"?(localStorage.nexUser||"nex"):q==="date"?new Date().toString():q==="clear"?"":"command not found");terminal.insertBefore(x,input.parentNode);input.value=""}}
function initBrowser(){const input=$("#url"),frame=$("#uvFrame"),status=$("#uvStatus");let ready=false;const makeUrl=()=>{let u=input.value.trim();if(!u)return null;if(!/^https?:\/\//i.test(u))u="https://www.google.com/search?q="+encodeURIComponent(u);input.value=u;return u};const start=async()=>{try{if(!("serviceWorker" in navigator))throw new Error("Service workers are unavailable");const reg=await navigator.serviceWorker.register("./service/sw.js",{scope:__uv$config.prefix});await navigator.serviceWorker.ready;ready=true;status.textContent="nexite • Ultraviolet ready";return true}catch(e){status.textContent="nexite • Ultraviolet failed";return false}};const open=async()=>{const u=makeUrl();if(!u)return;if(!ready&&!await start())return;frame.src=__uv$config.prefix+__uv$config.encodeUrl(u)};$("#go").onclick=open;$("#browserOpen").onclick=open;input.onkeydown=e=>{if(e.key==="Enter")open()};$("#back").onclick=()=>{try{frame.contentWindow.history.back()}catch{}};$("#forward").onclick=()=>{try{frame.contentWindow.history.forward()}catch{}};start()}
function startBoot(){try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>{})}catch{}power.classList.add("hidden");lock.classList.add("hidden");desktop.classList.add("hidden");boot.classList.remove("hidden");try{chime.currentTime=0;chime.play().catch(()=>{})}catch{}setTimeout(()=>{boot.classList.add("hidden");if(!localStorage.nexSetupDone){setup.classList.remove("hidden")}else{lock.classList.remove("hidden");$("#lockName").textContent=localStorage.nexDisplay||"nex";$("#unlockPass").value="";updateLockClock()}},1600)}
powerBtn.onclick=startBoot;
setupContinue.onclick=()=>{const name=$("#setupName").value.trim(),user=$("#setupUser").value.trim(),pass=$("#setupPass").value;if(!name||!user||!pass){setupContinue.textContent="fill in all three fields →";return}localStorage.nexSetupDone="1";localStorage.nexDisplay=name;localStorage.nexUser=user;localStorage.nexPass=pass;localStorage.nexSetupDone="1";setup.classList.add("hidden");desktop.classList.remove("hidden");openApp("about")};
$("#unlockBtn").onclick=()=>{const input=$("#unlockPass"),err=$("#unlockError");if(input.value===localStorage.nexPass){err.textContent="";input.value="";lock.classList.add("hidden");desktop.classList.remove("hidden");openApp("about")}else{err.textContent="incorrect password";input.value="";input.focus()}};
$("#unlockPass").onkeydown=e=>{if(e.key==="Enter")$("#unlockBtn").click()};$("#forgotBtn").onclick=async()=>{const ok=confirm("Reset nexOS? This will erase nexOS data for this site, including your account, notes, settings, and saved site data. It cannot erase your browser's global history or HTTP cache.");if(!ok)return;try{const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));if("serviceWorker" in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}}catch{}localStorage.clear();sessionStorage.clear();location.reload()};
populate();
const selection=document.createElement("div");selection.id="selectionBox";desktop.appendChild(selection);let selecting=null;desktop.addEventListener("pointerdown",e=>{if(e.target!==desktop&&e.target!==iconRoot)return;if(e.target.classList&&e.target.classList.contains("icon"))return;selecting=[e.clientX,e.clientY];selection.style.display="block";selection.style.left=e.clientX+"px";selection.style.top=e.clientY+"px";selection.style.width="0px";selection.style.height="0px";$$(".icon").forEach(x=>x.classList.remove("selected"))});desktop.addEventListener("pointermove",e=>{if(!selecting)return;const x=Math.min(selecting[0],e.clientX),y=Math.min(selecting[1],e.clientY),w=Math.abs(e.clientX-selecting[0]),h=Math.abs(e.clientY-selecting[1]);selection.style.left=x+"px";selection.style.top=y+"px";selection.style.width=w+"px";selection.style.height=h+"px";const sr=selection.getBoundingClientRect();$$(".icon").forEach(i=>{const r=i.getBoundingClientRect();if(r.left<sr.right&&r.right>sr.left&&r.top<sr.bottom&&r.bottom>sr.top)i.classList.add("selected")})});desktop.addEventListener("pointerup",()=>{selecting=null;selection.style.display="none"});